<?xml version="1.0"?>
<package format="3">
  <name>t870_cmd_bridge</name>
  <version>1.0.0</version>
  <description>Minimal T870 bridge: /cmd_drive and /cmd_wheel to Arduino serial</description>
  <maintainer email="urrc@example.com">URRC</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>python3-serial</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
